version: "3.9"
services:
  web:
    image: registry.piber.network/dev-node:v3.0.1
    ports:
      - "3000:3000"
    volumes:
      - ./../../:/var/www
    command: yarn --cwd /var/www/packages/web dev
    environment:
      - VIRTUAL_HOST=web.simcity
      - VIRTUAL_PORT=3000
networks:
  default:
    external:
      name: pbr-simcity-dev
