version: "3.9"
services:
  api:
    image: registry.piber.network/dev-node:v3.0.3
    ports:
      - "4000:4000"
    volumes:
      - ./../../:/var/www
    command: yarn --cwd /var/www/packages/api dev
    expose:
      - "4000"
    environment:
      - VIRTUAL_HOST=api.simcity
      - VIRTUAL_PORT=4000
networks:
  default:
    external:
      name: pbr-simcity-dev
